int main()
{
	throw exception();
	return 0;
}

